# Generated by Django 3.0.7 on 2020-07-18 06:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_todo_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 6, 3, 17, 725367, tzinfo=utc), null=True),
        ),
    ]
