# Generated by Django 3.0.7 on 2020-07-18 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0004_auto_20200718_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='last_date',
            field=models.TextField(default='yo'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 6, 54, 41, 508696, tzinfo=utc), null=True),
        ),
    ]
