# Generated by Django 3.0.7 on 2020-07-18 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0005_auto_20200718_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 7, 11, 53, 31309, tzinfo=utc), null=True),
        ),
    ]
