# Generated by Django 3.0.7 on 2020-07-19 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0010_auto_20200718_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='last_date',
            name='last_date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='last_date',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 10, 59, 45, 943, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='last_date',
            field=models.TextField(default='yo', null=True),
        ),
    ]
